channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcbio-gff=0.7.0
  - biopython=1.76
  - blast=2.15.0
  - cython=0.29.33
  - diamond=2.0.9
  - fasttree=2.1.11
  - freetype=2.12.1
  - glimmerhmm=3.0.4
  - helperlibs=0.2.1
  - hmmer=3.4
  - hmmer2=2.3.2
  - jinja2=2.11.1
  - markupsafe=2.0.1
  - matplotlib=3.5.3
  - muscle=5.1
  - prodigal=2.6.3
  - pyscss=1.4.0
  - pysvg-py3=0.2.2.post3
  - python=3.7.16
  - scikit-learn=1.0.2
